version: '3.8'

services:
  raiden-server:
    build:
      context: .
      target: server
    ports:
      - "5000:5000"
    volumes:
      - ./raiden_workspace_srv:/app/raiden_workspace_srv
      - ./.env:/app/.env
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - BRAVE_SEARCH_API_KEY=${BRAVE_SEARCH_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}

  raiden-desktop:
    build:
      context: .
      target: desktop
    volumes:
      - ./raiden_workspace_srv:/app/raiden_workspace_srv
      - ./.env:/app/.env
